theme: jekyll-theme-hacker
sass:
  style: compressed

title: [FrontEnd Direction materials]
description: [CURSOR Education https://cursor.education/. All rights reserved.]
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
